name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore ProductComponent dependencies
      run: dotnet restore CommunicationLayer/Components/ProductComponent/ProductComponent.csproj 
    - name: Build ProductComponent
      run: dotnet build CommunicationLayer/Components/ProductComponent/ProductComponent.csproj --no-restore
    - name: Test ProductComponent
      run: dotnet test CommunicationLayer/Components/ProductComponent/ProductComponent.csproj --no-build --verbosity normal
      
    - name: Restore OrderComponent dependencies
      run: dotnet restore CommunicationLayer/Components/OrderComponent/OrderComponent.csproj 
    - name: Build OrderComponent
      run: dotnet build CommunicationLayer/Components/OrderComponent/OrderComponent.csproj --no-restore
    - name: Test OrderComponent
      run: dotnet test CommunicationLayer/Components/OrderComponent/OrderComponent.csproj --no-build --verbosity normal
      
    - name: Restore WebGateway dependencies
      run: dotnet restore CommunicationLayer/Gateways/WebGateway/WebGateway.csproj 
    - name: Build WebGateway
      run: dotnet build CommunicationLayer/Gateways/WebGateway/WebGateway.csproj --no-restore
    - name: Test WebGateway
      run: dotnet test CommunicationLayer/Gateways/WebGateway/WebGateway.csproj --no-build --verbosity normal
