name: Review OrderComponent

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore OrderComponent dependencies
      run: dotnet restore CommunicationLayer/Components/OrderComponent/OrderComponent.csproj 
    - name: Build OrderComponent
      run: dotnet build CommunicationLayer/Components/OrderComponent/OrderComponent.csproj --no-restore
    - name: Test OrderComponent
      run: dotnet test CommunicationLayer/Components/OrderComponent/OrderComponent.csproj --no-build --verbosity normal
        
    - name: Docker Build & Push Action
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: 3739323298328/order-component
        # Target Docker registry
        registry: docker.io
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: CommunicationLayer/Components/OrderComponent/Dockerfile
        # Docker registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Docker registry password
        password: ${{ secrets.DOCKER_PASSWORD }}
    
